import { Avatar } from "antd";

export const testData = (users) => [
  {
    id: 1,
    image: "https://www.colgate.com/content/dam/cp-sites/oral-care/oral-care-center/global/general/products/sub-brands-latam/colgate-luminous-white-charcoal-thumb.jpg",
    title: "Colgate Luminous White Lovers Vino y Tabaco 70g",
    link: "https://www.colgate.com/es-co/products/toothpaste/colgate-luminous-white-carbon-activado",
    description: "Tu copa de vino ya no vendrá acompañada de la preocupación de las manchas en tus dientes. La nueva línea Colgate® Luminous White Lovers Vino & Tabaco te ayuda a mantener tu sonrisa más blanca porque remueve hasta las manchas más difíciles*, como las causadas por el vino y tabaco; así puedes disfrutar cada momento, sin preocuparse por las manchas y continuar sonriendo con confianza.",
    availableQuantity: 50,
    offeredPoints: 5000,
    validityDate: "31/12/2022",
    comments: [
      {
        avatar: <Avatar src={users[0].picture.large} />,
        name: users[0].name.first,
        content: "Este producto es increible",
      },
      {
        avatar: <Avatar src={users[1].picture.large} />,
        name: users[1].name.first,
        content: "Me gusto mucho",
      },
    ],
  },
  {
    id: 2,
    image: "https://www.colgate.com/content/dam/cp-sites/oral-care/oral-care-center/global/general/heros-2022/home-banner-natural-extracts-2022.jpg.rendition.1350.758.jpg",
    title: "Colgate® Natural Extracts Frutas Rojos y Açaí",
    link: "https://www.colgate.com/es-co/natural-extracts",
    description: "Disfruta de una increíble experiencia de sabor con la nueva crema dental Colgate® Natural Extracts Frutos Rojos y Açaí que cuida naturalmente tus dientes para lucir una sonrisa saludable en todo momento.",
    availableQuantity: 60,
    offeredPoints: 4500,
    validityDate: "31/12/2022",
    comments: [],
  },
  {
    id: 3,
    image: "https://superbuun.tu-mercado.co/imagenes/7701101244777.png",
    title: "Apanados de pechuga y pollo",
    link: "https://www.zenu.com.co/curiosidades/para-los-fanaticos-del-crocante-delicioso-de-los-apanados-zenu",
    description: "Si hay un sabor que todos aman y que nos hace 100% feliz, es el sabor de los Apanados de Pollo Zenú. Son hechos de Pollo 100% Pechuga y son tan deliciosos y fáciles de preparar que hacen de cada receta un momento especial.",
    availableQuantity: 20,
    offeredPoints: 4000,
    validityDate: "31/12/2022",
    comments: [],
  },
  {
    id: 4,
    image: "https://ranchera.com.co/wp-content/uploads/2022/07/recetas-03-810x0-c-default.webp",
    title: "Chorizo Ranchera",
    link: "https://ranchera.com.co/contenidos/como-preparar-chorizo-con-ranchera/",
    description: "Con Ranchera es super fácil preparar chorizo de diferentes maneras. Tanto con el CHORIZO PREMIUM RANCHERA  o con el CHORIZO PARRILLA RANCHERA, que están elaborados con carne de cerdo sabor ahumado y un toque picante, tienes infinidad de opciones para preparar recetas exquisitas.",
    availableQuantity: 50,
    offeredPoints: 3000,
    validityDate: "31/12/2022",
    comments: [],
  },
  {
    id: 5,
    image: "https://www.pietran.com.co/wp-content/uploads/2021/11/hamburguesa-de-salmon-con-hummus-pietran.webp",
    title: "Hamburguesa de Salmón con Hummus Pietrán",
    link: "https://www.pietran.com.co/hamburguesa-de-salmon-con-hummus-pietran/",
    description: "Todo el sabor de nuestro Hummus Pietrán en esta deliciosa receta, acompañada de salmón para darle a tu día el equilibrio perfecto entre práctico y delicioso. Esta hamburguesa es una buena opción si queremos comer algo diferente sin dejar de cuidarnos, ya que es ligera y la puedes disfrutar en un rico almuerzo o en una cena deliciosa.",
    availableQuantity: 50,
    offeredPoints: 5000,
    validityDate: "31/12/2022",
    comments: [],
  },
]